# Generated by Django 6.0.4 on 2026-05-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshippost',
            old_name='tittle',
            new_name='title',
        ),
    ]
